<?php
/**
 * TemplatesApi
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * SafetyCulture API
 *
 * The SafetyCulture API gives you direct access to your data in the SafetyCulture platform.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Swagger\Client\ApiException;
use Swagger\Client\Configuration;
use Swagger\Client\HeaderSelector;
use Swagger\Client\ObjectSerializer;

/**
 * TemplatesApi Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class TemplatesApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation templatesSearchGet
     *
     * Search modified templates
     *
     * @param  string[] $field Field(s) to retrieve (optional)
     * @param  string $order The datetime order in which the templates will be given (optional, default to asc)
     * @param  \DateTime $modified_after Templates should be last modified after this date and time (optional)
     * @param  \DateTime $modified_before Templates should be last modified before this date and time (optional)
     * @param  string $archived Flag indicating should templates be archived, non archived, or both (optional, default to false)
     * @param  string $owner Retrieve templates owned by me or shared with me by other users. Or all the templates I have access to. (optional, default to all)
     * @param  float $limit Maximum number of entries to return (optional, default to 1000)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function templatesSearchGet($field = null, $order = 'asc', $modified_after = null, $modified_before = null, $archived = 'false', $owner = 'all', $limit = '1000')
    {
        $this->templatesSearchGetWithHttpInfo($field, $order, $modified_after, $modified_before, $archived, $owner, $limit);
    }

    /**
     * Operation templatesSearchGetWithHttpInfo
     *
     * Search modified templates
     *
     * @param  string[] $field Field(s) to retrieve (optional)
     * @param  string $order The datetime order in which the templates will be given (optional, default to asc)
     * @param  \DateTime $modified_after Templates should be last modified after this date and time (optional)
     * @param  \DateTime $modified_before Templates should be last modified before this date and time (optional)
     * @param  string $archived Flag indicating should templates be archived, non archived, or both (optional, default to false)
     * @param  string $owner Retrieve templates owned by me or shared with me by other users. Or all the templates I have access to. (optional, default to all)
     * @param  float $limit Maximum number of entries to return (optional, default to 1000)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function templatesSearchGetWithHttpInfo($field = null, $order = 'asc', $modified_after = null, $modified_before = null, $archived = 'false', $owner = 'all', $limit = '1000')
    {
        $returnType = '';
        $request = $this->templatesSearchGetRequest($field, $order, $modified_after, $modified_before, $archived, $owner, $limit);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation templatesSearchGetAsync
     *
     * Search modified templates
     *
     * @param  string[] $field Field(s) to retrieve (optional)
     * @param  string $order The datetime order in which the templates will be given (optional, default to asc)
     * @param  \DateTime $modified_after Templates should be last modified after this date and time (optional)
     * @param  \DateTime $modified_before Templates should be last modified before this date and time (optional)
     * @param  string $archived Flag indicating should templates be archived, non archived, or both (optional, default to false)
     * @param  string $owner Retrieve templates owned by me or shared with me by other users. Or all the templates I have access to. (optional, default to all)
     * @param  float $limit Maximum number of entries to return (optional, default to 1000)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function templatesSearchGetAsync($field = null, $order = 'asc', $modified_after = null, $modified_before = null, $archived = 'false', $owner = 'all', $limit = '1000')
    {
        return $this->templatesSearchGetAsyncWithHttpInfo($field, $order, $modified_after, $modified_before, $archived, $owner, $limit)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation templatesSearchGetAsyncWithHttpInfo
     *
     * Search modified templates
     *
     * @param  string[] $field Field(s) to retrieve (optional)
     * @param  string $order The datetime order in which the templates will be given (optional, default to asc)
     * @param  \DateTime $modified_after Templates should be last modified after this date and time (optional)
     * @param  \DateTime $modified_before Templates should be last modified before this date and time (optional)
     * @param  string $archived Flag indicating should templates be archived, non archived, or both (optional, default to false)
     * @param  string $owner Retrieve templates owned by me or shared with me by other users. Or all the templates I have access to. (optional, default to all)
     * @param  float $limit Maximum number of entries to return (optional, default to 1000)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function templatesSearchGetAsyncWithHttpInfo($field = null, $order = 'asc', $modified_after = null, $modified_before = null, $archived = 'false', $owner = 'all', $limit = '1000')
    {
        $returnType = '';
        $request = $this->templatesSearchGetRequest($field, $order, $modified_after, $modified_before, $archived, $owner, $limit);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'templatesSearchGet'
     *
     * @param  string[] $field Field(s) to retrieve (optional)
     * @param  string $order The datetime order in which the templates will be given (optional, default to asc)
     * @param  \DateTime $modified_after Templates should be last modified after this date and time (optional)
     * @param  \DateTime $modified_before Templates should be last modified before this date and time (optional)
     * @param  string $archived Flag indicating should templates be archived, non archived, or both (optional, default to false)
     * @param  string $owner Retrieve templates owned by me or shared with me by other users. Or all the templates I have access to. (optional, default to all)
     * @param  float $limit Maximum number of entries to return (optional, default to 1000)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function templatesSearchGetRequest($field = null, $order = 'asc', $modified_after = null, $modified_before = null, $archived = 'false', $owner = 'all', $limit = '1000')
    {
        if ($limit !== null && $limit > 1000) {
            throw new \InvalidArgumentException('invalid value for "$limit" when calling TemplatesApi.templatesSearchGet, must be smaller than or equal to 1000.');
        }
        if ($limit !== null && $limit < 1) {
            throw new \InvalidArgumentException('invalid value for "$limit" when calling TemplatesApi.templatesSearchGet, must be bigger than or equal to 1.');
        }


        $resourcePath = '/templates/search';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if (is_array($field)) {
            $field = ObjectSerializer::serializeCollection($field, 'csv', true);
        }
        if ($field !== null) {
            $queryParams['field'] = ObjectSerializer::toQueryValue($field);
        }
        // query params
        if ($order !== null) {
            $queryParams['order'] = ObjectSerializer::toQueryValue($order);
        }
        // query params
        if ($modified_after !== null) {
            $queryParams['modified_after'] = ObjectSerializer::toQueryValue($modified_after);
        }
        // query params
        if ($modified_before !== null) {
            $queryParams['modified_before'] = ObjectSerializer::toQueryValue($modified_before);
        }
        // query params
        if ($archived !== null) {
            $queryParams['archived'] = ObjectSerializer::toQueryValue($archived);
        }
        // query params
        if ($owner !== null) {
            $queryParams['owner'] = ObjectSerializer::toQueryValue($owner);
        }
        // query params
        if ($limit !== null) {
            $queryParams['limit'] = ObjectSerializer::toQueryValue($limit);
        }


        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
