<?php
/**
 * AuditIdItemIdCreatedByStatusPriorityAssigneesDueAtCreatedAtModifiedAtMatchTextOffsetLimitModelTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * SafetyCulture API
 *
 * The SafetyCulture API gives you direct access to your data in the SafetyCulture platform.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * AuditIdItemIdCreatedByStatusPriorityAssigneesDueAtCreatedAtModifiedAtMatchTextOffsetLimitModelTest Class Doc Comment
 *
 * @category    Class
 * @description AuditIdItemIdCreatedByStatusPriorityAssigneesDueAtCreatedAtModifiedAtMatchTextOffsetLimitModel
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AuditIdItemIdCreatedByStatusPriorityAssigneesDueAtCreatedAtModifiedAtMatchTextOffsetLimitModelTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "AuditIdItemIdCreatedByStatusPriorityAssigneesDueAtCreatedAtModifiedAtMatchTextOffsetLimitModel"
     */
    public function testAuditIdItemIdCreatedByStatusPriorityAssigneesDueAtCreatedAtModifiedAtMatchTextOffsetLimitModel()
    {
    }

    /**
     * Test attribute "audit_id"
     */
    public function testPropertyAuditId()
    {
    }

    /**
     * Test attribute "item_id"
     */
    public function testPropertyItemId()
    {
    }

    /**
     * Test attribute "created_by"
     */
    public function testPropertyCreatedBy()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }

    /**
     * Test attribute "priority"
     */
    public function testPropertyPriority()
    {
    }

    /**
     * Test attribute "assignees"
     */
    public function testPropertyAssignees()
    {
    }

    /**
     * Test attribute "due_at"
     */
    public function testPropertyDueAt()
    {
    }

    /**
     * Test attribute "created_at"
     */
    public function testPropertyCreatedAt()
    {
    }

    /**
     * Test attribute "modified_at"
     */
    public function testPropertyModifiedAt()
    {
    }

    /**
     * Test attribute "match_text"
     */
    public function testPropertyMatchText()
    {
    }

    /**
     * Test attribute "offset"
     */
    public function testPropertyOffset()
    {
    }

    /**
     * Test attribute "limit"
     */
    public function testPropertyLimit()
    {
    }
}
