<?php
/**
 * AuditsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * SafetyCulture API
 *
 * The SafetyCulture API gives you direct access to your data in the SafetyCulture platform.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * AuditsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class AuditsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for auditsAuditIdDeepLinkPost
     *
     * Generate a link to the audit.
     *
     */
    public function testAuditsAuditIdDeepLinkPost()
    {
    }

    /**
     * Test case for auditsAuditIdExportPost
     *
     * Export an audit report.
     *
     */
    public function testAuditsAuditIdExportPost()
    {
    }

    /**
     * Test case for auditsAuditIdExportsExportIdFilenameGet
     *
     * Download an audit report.
     *
     */
    public function testAuditsAuditIdExportsExportIdFilenameGet()
    {
    }

    /**
     * Test case for auditsAuditIdExportsExportIdGet
     *
     * Check the status of the export request submitted earlier.
     *
     */
    public function testAuditsAuditIdExportsExportIdGet()
    {
    }

    /**
     * Test case for auditsAuditIdGet
     *
     * Get a particular audit.
     *
     */
    public function testAuditsAuditIdGet()
    {
    }

    /**
     * Test case for auditsAuditIdMediaMediaIdGet
     *
     * Get a media item associated with an audit.
     *
     */
    public function testAuditsAuditIdMediaMediaIdGet()
    {
    }

    /**
     * Test case for auditsAuditIdPut
     *
     * Updates a particular audit.
     *
     */
    public function testAuditsAuditIdPut()
    {
    }

    /**
     * Test case for auditsAuditIdSharePost
     *
     * Share an audit.
     *
     */
    public function testAuditsAuditIdSharePost()
    {
    }

    /**
     * Test case for auditsAuditIdWebReportLinkDelete
     *
     * Delete the link to the web report of the audit.
     *
     */
    public function testAuditsAuditIdWebReportLinkDelete()
    {
    }

    /**
     * Test case for auditsAuditIdWebReportLinkGet
     *
     * Retrieve a link to the web report of the audit.
     *
     */
    public function testAuditsAuditIdWebReportLinkGet()
    {
    }

    /**
     * Test case for auditsPost
     *
     * Start an audit.
     *
     */
    public function testAuditsPost()
    {
    }

    /**
     * Test case for auditsSearchGet
     *
     * Search modified audits.
     *
     */
    public function testAuditsSearchGet()
    {
    }
}
