<?php
/**
 * GroupsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * SafetyCulture API
 *
 * The SafetyCulture API gives you direct access to your data in the SafetyCulture platform.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * GroupsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class GroupsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for groupsGet
     *
     * Lists all the groups in an org.
     *
     */
    public function testGroupsGet()
    {
    }

    /**
     * Test case for groupsGroupIdUsersGet
     *
     * Lists all the users.
     *
     */
    public function testGroupsGroupIdUsersGet()
    {
    }

    /**
     * Test case for groupsGroupIdUsersPost
     *
     * Adds a user to a group.
     *
     */
    public function testGroupsGroupIdUsersPost()
    {
    }

    /**
     * Test case for groupsPost
     *
     * Create a group.
     *
     */
    public function testGroupsPost()
    {
    }

    /**
     * Test case for groupsRoleIdUsersUserIdDelete
     *
     * Removes a user from the group with the specified role ID.
     *
     */
    public function testGroupsRoleIdUsersUserIdDelete()
    {
    }
}
