<?php
/**
 * ResponseSetsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * SafetyCulture API
 *
 * The SafetyCulture API gives you direct access to your data in the SafetyCulture platform.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * ResponseSetsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ResponseSetsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for responseSetsGet
     *
     * Retrieves all response sets in the requesting user's organisation.
     *
     */
    public function testResponseSetsGet()
    {
    }

    /**
     * Test case for responseSetsIdDelete
     *
     * Deletes a response set with the specified response ID.
     *
     */
    public function testResponseSetsIdDelete()
    {
    }

    /**
     * Test case for responseSetsIdGet
     *
     * Retrieves the response set with the given response set ID.
     *
     */
    public function testResponseSetsIdGet()
    {
    }

    /**
     * Test case for responseSetsIdPut
     *
     * Updates a response set.
     *
     */
    public function testResponseSetsIdPut()
    {
    }

    /**
     * Test case for responseSetsIdResponsesPost
     *
     * Creates a response.
     *
     */
    public function testResponseSetsIdResponsesPost()
    {
    }

    /**
     * Test case for responseSetsIdResponsesResponseIdDelete
     *
     * Deletes a response.
     *
     */
    public function testResponseSetsIdResponsesResponseIdDelete()
    {
    }

    /**
     * Test case for responseSetsIdResponsesResponseIdPut
     *
     * Updates a response.
     *
     */
    public function testResponseSetsIdResponsesResponseIdPut()
    {
    }

    /**
     * Test case for responseSetsPost
     *
     * Creates a new response set.
     *
     */
    public function testResponseSetsPost()
    {
    }
}
