<?php
/**
 * WorkflowsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * SafetyCulture API
 *
 * The SafetyCulture API gives you direct access to your data in the SafetyCulture platform.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * WorkflowsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class WorkflowsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for workflowsGet
     *
     * Retrieves all registered workflows.
     *
     */
    public function testWorkflowsGet()
    {
    }

    /**
     * Test case for workflowsPost
     *
     * Registers a new workflow.
     *
     */
    public function testWorkflowsPost()
    {
    }

    /**
     * Test case for workflowsWorkflowIdDelete
     *
     * Deletes a specified workflow.
     *
     */
    public function testWorkflowsWorkflowIdDelete()
    {
    }

    /**
     * Test case for workflowsWorkflowIdGet
     *
     * Retrieves a specified workflow.
     *
     */
    public function testWorkflowsWorkflowIdGet()
    {
    }

    /**
     * Test case for workflowsWorkflowIdPut
     *
     * Updates a specified workflow.
     *
     */
    public function testWorkflowsWorkflowIdPut()
    {
    }
}
